apiVersion: v1
kind: Pod
metadata:
  name: master-nginx
  labels:
    app: master-nginx
spec:
  containers:
  - name: master-nginx
    image: faizanmomin2508/cloudethix_master_nginx_faizan:v1
    ports:
      - containerPort: 80
